pipeline {
    agent any

   stage('Clone Repo') {
    steps {
        git url: 'https://github.com/devanshsengar04/plant-disease.git', branch: 'main'
    }
}


        stage('Navigate to Project') {
            steps {
                dir('Plant-Disease-Classifier-main') {
                    echo 'Navigated into project directory.'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Plant-Disease-Classifier-main') {
                    sh 'docker build -t ml-app .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker run -d -p 8501:8501 --name ml-container ml-app || echo "Container already running"'
            }
        }
    }
}
